// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ8pFDFwPItSt_Udukezh98-ocou0ASXg',
    appId: '1:6111565043:web:e36c46024e81707a211386',
    messagingSenderId: '6111565043',
    projectId: 'utmost-test-d4122',
    authDomain: 'utmost-test-d4122.firebaseapp.com',
    storageBucket: 'utmost-test-d4122.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW2man2NKUuR6YdBJSmEumSZGU1a4Rjq0',
    appId: '1:6111565043:android:23f0d82f5d64ca6e211386',
    messagingSenderId: '6111565043',
    projectId: 'utmost-test-d4122',
    storageBucket: 'utmost-test-d4122.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcRAB7fF2eyOxYU8-B-2O7XaMmuixzYf4',
    appId: '1:6111565043:ios:8ae6c2c4fab3a4ab211386',
    messagingSenderId: '6111565043',
    projectId: 'utmost-test-d4122',
    storageBucket: 'utmost-test-d4122.appspot.com',
    iosBundleId: 'com.example.utmostTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcRAB7fF2eyOxYU8-B-2O7XaMmuixzYf4',
    appId: '1:6111565043:ios:47e557bd2e9fcb68211386',
    messagingSenderId: '6111565043',
    projectId: 'utmost-test-d4122',
    storageBucket: 'utmost-test-d4122.appspot.com',
    iosBundleId: 'com.example.utmostTest.RunnerTests',
  );
}
